In [43]:
import polars as pl

bekleyen_file = r"..\data\Bekleyen_Siparisler.xlsx"
hazir_file = r"..\data\Hazir_Siparisler.xlsx"

# 1. Read files directly into Polars as Strings
pd_bekleyen = pl.read_excel(bekleyen_file, infer_schema_length=0)
pd_hazir = pl.read_excel(hazir_file, infer_schema_length=0)

# 2. Combine them vertically
# We use how="vertical" because we forced everything to String, 
# so the schemas will match perfectly now.
sales_df = pl.concat([pd_bekleyen, pd_hazir], how="vertical")

print(sales_df.columns)

"""                pd_bekleyen = pd.read_excel(bekleyen_file)
                pd_hazir = pd.read_excel(hazir_file)
                combined_pd = pd.concat([pd_bekleyen, pd_hazir], ignore_index=True)
                self.sales_df = pl.from_pandas(combined_pd)"""

['SDM Kodu', 'SDM', 'NOKTA Kodu', 'NOKTA', 'SATIŞ TEMSİLCİSİ Kodu', 'SATIŞ TEMSİLCİSİ', 'ÜRÜN Kodu', 'ÜRÜN', 'Eski Müşteri ID', 'Erp Sevkiyat', 'Erp Fatura', 'Miktar', 'Fatura Sayısı', 'FKMS', 'Kg', 'Brüt Tutar', 'Nokta İskontosu', 'Kampanya', 'Diğer Bedelsiz', 'Toplam İndirim', 'Net Tutar', 'KDV', 'Genel Toplam', 'Kapı Sayısı']

'                pd_bekleyen = pd.read_excel(bekleyen_file)\n                pd_hazir = pd.read_excel(hazir_file)\n                combined_pd = pd.concat([pd_bekleyen, pd_hazir], ignore_index=True)\n                self.sales_df = pl.from_pandas(combined_pd)'

In [ ]:
import polars as pl

bekleyen_file = r"..\data\Bekleyen_Siparisler.xlsx"
hazir_file = r"..\data\Hazir_Siparisler.xlsx"

df = pl.read_excel(bekleyen_file)
bekleyen_df=df.with_columns(
    pl.lit("waiting").cast(pl.Utf8).alias("status")
)
df2 = pl.read_excel(hazir_file)
hazir_df=df2.with_columns(
    pl.lit("ready").cast(pl.Utf8).alias("status")
)
df3 = pl.concat([bekleyen_df, hazir_df], how="vertical_relaxed")
birlesik_df=df3.with_columns(
    pl.col("Miktar").cast(pl.Int64),
    pl.col("Fatura Sayısı").cast(pl.Int64),
    pl.col("FKMS").cast(pl.Int64),
    pl.col("Genel Toplam").cast(pl.Float64),
    pl.col("SATIŞ TEMSİLCİSİ Kodu").cast(pl.Utf8),
    pl.col("SATIŞ TEMSİLCİSİ").cast(pl.Utf8),
    pl.col("NOKTA Kodu").cast(pl.Utf8),
    pl.col("NOKTA").cast(pl.Utf8),
    pl.col("ÜRÜN Kodu").cast(pl.Utf8),
    pl.col("ÜRÜN").cast(pl.Utf8)
)
birlesik_df = birlesik_df.select(
    pl.col("SATIŞ TEMSİLCİSİ Kodu"),
    pl.col("SATIŞ TEMSİLCİSİ"),
    pl.col("NOKTA Kodu"),
    pl.col("NOKTA"),
    pl.col("ÜRÜN Kodu"),
    pl.col("ÜRÜN"),
    pl.col("Miktar"),
    pl.col("Fatura Sayısı"),
    pl.col("Genel Toplam")
)


birlesik_df = birlesik_df.filter(pl.col("SATIŞ TEMSİLCİSİ Kodu").is_not_null())


customer_file = r"..\data\müşteri listesi.xlsx"
pallet_file =r"..\data\palet koli raporu.xlsx"

Could not determine dtype for column 9, falling back to string
Could not determine dtype for column 10, falling back to string
Could not determine dtype for column 23, falling back to string
Could not determine dtype for column 9, falling back to string
Could not determine dtype for column 10, falling back to string
Could not determine dtype for column 23, falling back to string

In [45]:
birlesik_df

shape: (2_463, 9)
┌────────────┬────────────┬────────────┬────────────┬───┬────────────┬────────┬────────┬───────────┐
│ SATIŞ      ┆ SATIŞ      ┆ NOKTA Kodu ┆ NOKTA      ┆ … ┆ ÜRÜN       ┆ Miktar ┆ Fatura ┆ Genel     │
│ TEMSİLCİSİ ┆ TEMSİLCİSİ ┆ ---        ┆ ---        ┆   ┆ ---        ┆ ---    ┆ Sayısı ┆ Toplam    │
│ Kodu       ┆ ---        ┆ str        ┆ str        ┆   ┆ str        ┆ i64    ┆ ---    ┆ ---       │
│ ---        ┆ str        ┆            ┆            ┆   ┆            ┆        ┆ i64    ┆ f64       │
│ str        ┆            ┆            ┆            ┆   ┆            ┆        ┆        ┆           │
╞════════════╪════════════╪════════════╪════════════╪═══╪════════════╪════════╪════════╪═══════════╡
│ 37356      ┆ SERAY      ┆ 6107180    ┆ A.KORKMAZ  ┆ … ┆ BEYPAZARI  ┆ 5      ┆ 0      ┆ 1074.99   │
│            ┆ AKSOY      ┆            ┆ DIŞ TİC.   ┆   ┆ SADE MADEN ┆        ┆        ┆           │
│            ┆            ┆            ┆ LTD. ŞTİ.  ┆   ┆ SUYU       ┆        ┆        ┆           │
│ 37356      ┆ SERAY      ┆ 6107180    ┆ A.KORKMAZ  ┆ … ┆ CAN LIP    ┆ 1      ┆ 0      ┆ 925.87    │
│            ┆ AKSOY      ┆            ┆ DIŞ TİC.   ┆   ┆ SEFT 330ML ┆        ┆        ┆           │
│            ┆            ┆            ┆ LTD. ŞTİ.  ┆   ┆ 24X PROMO  ┆        ┆        ┆           │
│            ┆            ┆            ┆            ┆   ┆ S…         ┆        ┆        ┆           │
│ 37356      ┆ SERAY      ┆ 6107180    ┆ A.KORKMAZ  ┆ … ┆ CAN LIP    ┆ 1      ┆ 0      ┆ 323.98    │
│            ┆ AKSOY      ┆            ┆ DIŞ TİC.   ┆   ┆ SPARK      ┆        ┆        ┆           │
│            ┆            ┆            ┆ LTD. ŞTİ.  ┆   ┆ TRPKL      ┆        ┆        ┆           │
│            ┆            ┆            ┆            ┆   ┆ 330ML 12X  ┆        ┆        ┆           │
│ 37356      ┆ SERAY      ┆ 6107180    ┆ A.KORKMAZ  ┆ … ┆ CAN PC     ┆ 2      ┆ 0      ┆ 692.99    │
│            ┆ AKSOY      ┆            ┆ DIŞ TİC.   ┆   ┆ KOLA 200ML ┆        ┆        ┆           │
│            ┆            ┆            ┆ LTD. ŞTİ.  ┆   ┆ 12X        ┆        ┆        ┆           │
│            ┆            ┆            ┆            ┆   ┆ 100KCAL …  ┆        ┆        ┆           │
│ 37356      ┆ SERAY      ┆ 6107180    ┆ A.KORKMAZ  ┆ … ┆ CAN PC     ┆ 1      ┆ 0      ┆ 864.36    │
│            ┆ AKSOY      ┆            ┆ DIŞ TİC.   ┆   ┆ KOLA 330ML ┆        ┆        ┆           │
│            ┆            ┆            ┆ LTD. ŞTİ.  ┆   ┆ 24X SLEEK  ┆        ┆        ┆           │
│            ┆            ┆            ┆            ┆   ┆ 10…        ┆        ┆        ┆           │
│ …          ┆ …          ┆ …          ┆ …          ┆ … ┆ …          ┆ …      ┆ …      ┆ …         │
│ 34759      ┆ MUSTAFA    ┆ 5649284    ┆ ŞENEL      ┆ … ┆ CAN PC     ┆ 1      ┆ 1      ┆ 960.4     │
│            ┆ DELİLOĞLU  ┆            ┆ MERVE      ┆   ┆ KOLA 330ML ┆        ┆        ┆           │
│            ┆            ┆            ┆ MORALI     ┆   ┆ 24X SLEEK  ┆        ┆        ┆           │
│            ┆            ┆            ┆            ┆   ┆ 10…        ┆        ┆        ┆           │
│ 37511      ┆ ASLI OFLAZ ┆ 6109222    ┆ ŞENOL      ┆ … ┆ PET PC     ┆ 6      ┆ 1      ┆ 3599.83   │
│            ┆            ┆            ┆ ŞABANOĞLU  ┆   ┆ KOLA 1.5L  ┆        ┆        ┆           │
│            ┆            ┆            ┆            ┆   ┆ 12X 70KCAL ┆        ┆        ┆           │
│ 38041      ┆ ONUR CAN   ┆ 5479573    ┆ ŞİBEN      ┆ … ┆ CAN PC     ┆ 3      ┆ 1      ┆ 2881.2    │
│            ┆ DİKBAŞ     ┆            ┆ KEREMOĞLU  ┆   ┆ KOLA 330ML ┆        ┆        ┆           │
│            ┆            ┆            ┆            ┆   ┆ 24X SLEEK  ┆        ┆        ┆           │
│            ┆            ┆            ┆            ┆   ┆ 10…        ┆        ┆        ┆           │
│ 38041      ┆ ONUR CAN   ┆ 5479573    ┆ ŞİBEN      ┆ … ┆ PET PC     ┆ 3      ┆ 1      ┆ 1776.54   │
│            ┆ DİKBAŞ     ┆            ┆ KEREMOĞLU  ┆   ┆ KOLA 1L    ┆        ┆        ┆           │
│            ┆            ┆            ┆            ┆   ┆ 12X 70KCAL ┆        ┆        ┆           │
│ 38041      ┆ ONUR CAN   ┆ 5479573    ┆ ŞİBEN      ┆ … ┆ PET PC     ┆ 3      ┆ 1      ┆ 1313.23   │
│            ┆ DİKBAŞ     ┆            ┆ KEREMOĞLU  ┆   ┆ KOLA 2.5L  ┆        ┆        ┆           │
│            ┆            ┆            ┆            ┆   ┆ 6X 100KCAL ┆        ┆        ┆           │
│            ┆            ┆            ┆            ┆   ┆ DR…        ┆        ┆        ┆           │
└────────────┴────────────┴────────────┴────────────┴───┴────────────┴────────┴────────┴───────────┘

In [46]:
customer_file

'..\\data\\müşteri listesi.xlsx'

In [47]:
birlesik_df

shape: (2_463, 9)
┌────────────┬────────────┬────────────┬────────────┬───┬────────────┬────────┬────────┬───────────┐
│ SATIŞ      ┆ SATIŞ      ┆ NOKTA Kodu ┆ NOKTA      ┆ … ┆ ÜRÜN       ┆ Miktar ┆ Fatura ┆ Genel     │
│ TEMSİLCİSİ ┆ TEMSİLCİSİ ┆ ---        ┆ ---        ┆   ┆ ---        ┆ ---    ┆ Sayısı ┆ Toplam    │
│ Kodu       ┆ ---        ┆ str        ┆ str        ┆   ┆ str        ┆ i64    ┆ ---    ┆ ---       │
│ ---        ┆ str        ┆            ┆            ┆   ┆            ┆        ┆ i64    ┆ f64       │
│ str        ┆            ┆            ┆            ┆   ┆            ┆        ┆        ┆           │
╞════════════╪════════════╪════════════╪════════════╪═══╪════════════╪════════╪════════╪═══════════╡
│ 37356      ┆ SERAY      ┆ 6107180    ┆ A.KORKMAZ  ┆ … ┆ BEYPAZARI  ┆ 5      ┆ 0      ┆ 1074.99   │
│            ┆ AKSOY      ┆            ┆ DIŞ TİC.   ┆   ┆ SADE MADEN ┆        ┆        ┆           │
│            ┆            ┆            ┆ LTD. ŞTİ.  ┆   ┆ SUYU       ┆        ┆        ┆           │
│ 37356      ┆ SERAY      ┆ 6107180    ┆ A.KORKMAZ  ┆ … ┆ CAN LIP    ┆ 1      ┆ 0      ┆ 925.87    │
│            ┆ AKSOY      ┆            ┆ DIŞ TİC.   ┆   ┆ SEFT 330ML ┆        ┆        ┆           │
│            ┆            ┆            ┆ LTD. ŞTİ.  ┆   ┆ 24X PROMO  ┆        ┆        ┆           │
│            ┆            ┆            ┆            ┆   ┆ S…         ┆        ┆        ┆           │
│ 37356      ┆ SERAY      ┆ 6107180    ┆ A.KORKMAZ  ┆ … ┆ CAN LIP    ┆ 1      ┆ 0      ┆ 323.98    │
│            ┆ AKSOY      ┆            ┆ DIŞ TİC.   ┆   ┆ SPARK      ┆        ┆        ┆           │
│            ┆            ┆            ┆ LTD. ŞTİ.  ┆   ┆ TRPKL      ┆        ┆        ┆           │
│            ┆            ┆            ┆            ┆   ┆ 330ML 12X  ┆        ┆        ┆           │
│ 37356      ┆ SERAY      ┆ 6107180    ┆ A.KORKMAZ  ┆ … ┆ CAN PC     ┆ 2      ┆ 0      ┆ 692.99    │
│            ┆ AKSOY      ┆            ┆ DIŞ TİC.   ┆   ┆ KOLA 200ML ┆        ┆        ┆           │
│            ┆            ┆            ┆ LTD. ŞTİ.  ┆   ┆ 12X        ┆        ┆        ┆           │
│            ┆            ┆            ┆            ┆   ┆ 100KCAL …  ┆        ┆        ┆           │
│ 37356      ┆ SERAY      ┆ 6107180    ┆ A.KORKMAZ  ┆ … ┆ CAN PC     ┆ 1      ┆ 0      ┆ 864.36    │
│            ┆ AKSOY      ┆            ┆ DIŞ TİC.   ┆   ┆ KOLA 330ML ┆        ┆        ┆           │
│            ┆            ┆            ┆ LTD. ŞTİ.  ┆   ┆ 24X SLEEK  ┆        ┆        ┆           │
│            ┆            ┆            ┆            ┆   ┆ 10…        ┆        ┆        ┆           │
│ …          ┆ …          ┆ …          ┆ …          ┆ … ┆ …          ┆ …      ┆ …      ┆ …         │
│ 34759      ┆ MUSTAFA    ┆ 5649284    ┆ ŞENEL      ┆ … ┆ CAN PC     ┆ 1      ┆ 1      ┆ 960.4     │
│            ┆ DELİLOĞLU  ┆            ┆ MERVE      ┆   ┆ KOLA 330ML ┆        ┆        ┆           │
│            ┆            ┆            ┆ MORALI     ┆   ┆ 24X SLEEK  ┆        ┆        ┆           │
│            ┆            ┆            ┆            ┆   ┆ 10…        ┆        ┆        ┆           │
│ 37511      ┆ ASLI OFLAZ ┆ 6109222    ┆ ŞENOL      ┆ … ┆ PET PC     ┆ 6      ┆ 1      ┆ 3599.83   │
│            ┆            ┆            ┆ ŞABANOĞLU  ┆   ┆ KOLA 1.5L  ┆        ┆        ┆           │
│            ┆            ┆            ┆            ┆   ┆ 12X 70KCAL ┆        ┆        ┆           │
│ 38041      ┆ ONUR CAN   ┆ 5479573    ┆ ŞİBEN      ┆ … ┆ CAN PC     ┆ 3      ┆ 1      ┆ 2881.2    │
│            ┆ DİKBAŞ     ┆            ┆ KEREMOĞLU  ┆   ┆ KOLA 330ML ┆        ┆        ┆           │
│            ┆            ┆            ┆            ┆   ┆ 24X SLEEK  ┆        ┆        ┆           │
│            ┆            ┆            ┆            ┆   ┆ 10…        ┆        ┆        ┆           │
│ 38041      ┆ ONUR CAN   ┆ 5479573    ┆ ŞİBEN      ┆ … ┆ PET PC     ┆ 3      ┆ 1      ┆ 1776.54   │
│            ┆ DİKBAŞ     ┆            ┆ KEREMOĞLU  ┆   ┆ KOLA 1L    ┆        ┆        ┆           │
│            ┆            ┆            ┆            ┆   ┆ 12X 70KCAL ┆        ┆        ┆           │
│ 38041      ┆ ONUR CAN   ┆ 5479573    ┆ ŞİBEN      ┆ … ┆ PET PC     ┆ 3      ┆ 1      ┆ 1313.23   │
│            ┆ DİKBAŞ     ┆            ┆ KEREMOĞLU  ┆   ┆ KOLA 2.5L  ┆        ┆        ┆           │
│            ┆            ┆            ┆            ┆   ┆ 6X 100KCAL ┆        ┆        ┆           │
│            ┆            ┆            ┆            ┆   ┆ DR…        ┆        ┆        ┆           │
└────────────┴────────────┴────────────┴────────────┴───┴────────────┴────────┴────────┴───────────┘

In [48]:
import sys
import os

# 1. Get the directory of the current notebook (backend/data/)
notebook_dir = os.getcwd()

# 2. Get the path to the backend folder (one level up)
# '..' means go up one level from backend/data/ to backend/
project_root = os.path.abspath(os.path.join(notebook_dir, ".."))

# 3. Add it to the path ONLY if it's not already there
if project_root not in sys.path:
    sys.path.append(project_root)
    print(f"Successfully added {project_root} to the search path.")

In [49]:
print(project_root)

from services.palet_sayisi import Palet_Hesaplama
from services.konumlar import Konumlar_Hesaplama
import polars as pl

customer_file = r"C:\Users\user\Desktop\TS-Main\backend\data\Müşteri Listesi.xlsx"
pallet_file =r"C:\Users\user\Desktop\TS-Main\backend\data\Palet Koli Raporu.xlsx"

customer_df = pl.read_excel(customer_file)
pallet_df = pl.read_excel(pallet_file)
df= Palet_Hesaplama(birlesik_df,customer_df,pallet_df)
konumlar = Konumlar_Hesaplama(birlesik_df,customer_df,pallet_df)
konumlar

c:\Users\user\Desktop\TS-Main\backend

Could not determine dtype for column 4, falling back to string
Could not determine dtype for column 5, falling back to string
Could not determine dtype for column 7, falling back to string
Could not determine dtype for column 27, falling back to string
Could not determine dtype for column 50, falling back to string
Could not determine dtype for column 51, falling back to string
Could not determine dtype for column 52, falling back to string
Could not determine dtype for column 53, falling back to string
Could not determine dtype for column 54, falling back to string
Could not determine dtype for column 55, falling back to string
Could not determine dtype for column 57, falling back to string
Could not determine dtype for column 74, falling back to string
Could not determine dtype for column 75, falling back to string
Could not determine dtype for column 77, falling back to string
Could not determine dtype for column 96, falling back to string
Could not determine dtype for column 97, falling back to string
Could not determine dtype for column 7, falling back to string
Could not determine dtype for column 8, falling back to string
Could not determine dtype for column 9, falling back to string

Palet hesaplama hatası: column with name 'NOKTA_Kodu' has more than one occurrence

Resolved plan until failure:

	---> FAILED HERE RESOLVING 'sink' <---
DF ["NOKTA_Kodu", "NOKTA", "SATIŞ_TEMSİLCİSİ", "ÜRÜN_Kodu", ...]; PROJECT */10 COLUMNS
Konumlar hesaplama hatası: column with name 'id' has more than one occurrence

Resolved plan until failure:

	---> FAILED HERE RESOLVING 'sink' <---
DF ["id", "NOKTA", "SATIŞ_TEMSİLCİSİ", "ÜRÜN_Kodu", ...]; PROJECT */10 COLUMNS

Empty DataFrame
Columns: []
Index: []

In [42]:
df

Empty DataFrame
Columns: []
Index: []